name: Review requested
on:
  pull_request_target:
    types: [review_requested]
jobs:
  review-label:
    runs-on: ubuntu-latest
    steps:
    - uses: actions-ecosystem/action-add-labels@v1
      if: github.event.review.state == 'changes_requested'
      with:
        github_token: "${{ secrets.GITHUB_TOKEN }}"
        labels: todo
    - uses: actions-ecosystem/action-add-labels@v1
      if: github.event.review.state == 'approved'
      with:
        github_token: "${{ secrets.GITHUB_TOKEN }}"
        labels: approved
